name: MEXC Futures Signal Bot

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Kod deposunu klonla
        uses: actions/checkout@v4

      - name: Python kur
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Kütüphaneleri yükle
        run: pip install requests pandas numpy

      - name: Sinyal botunu çalıştır
        run: python main.py
