name: MEXC Signals Bot

on:
  schedule:
    - cron: "*/15 * * * *"   # Her 15 dakikada bir çalışır
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Repo'yu klonla
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Bağımlılıkları yükle
        run: |
          pip install requests pandas

      - name: Botu çalıştır
        run: python main.py
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
