name: Mum Bot Otomatik Çalıştırma

on:
  schedule:
    # Her 15 dakikada bir çalıştır
    - cron: "*/15 * * * *"
  workflow_dispatch:  # İstersen manuel çalıştırma için de
    inputs: {}

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Repo'yu checkout et
        uses: actions/checkout@v3

      - name: Python kur
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Paketleri yükle
        run: |
          python -m pip install --upgrade pip
          pip install pandas requests matplotlib

      - name: Mum Botu Çalıştır
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: |
          python main.py
